//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 02:29:46 PM MSK 
//


package com.shchuryk.xml.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Excursion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Excursion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/vouchers}VoucherBuilderFactory">
 *       &lt;sequence>
 *         &lt;element name="place" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Excursion", propOrder = {
    "place"
})
public class Excursion
    extends Voucher
{

    @Override
    public String toString() {
        return "Excursion{" +
                ", id='" + id + '\'' +
                ", country='" + country + '\'' +
                ", numberDays=" + numberDays +
                ", cost=" + cost +
                ", transportType=" + transportType +
                '}';
    }

    public String toSecondaryString() {
        return "place=" + place;
    }

    @XmlElement(required = true)
    protected String place;

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

}
