//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 02:29:46 PM MSK 
//


package com.shchuryk.xml.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.vouchers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Voucher_QNAME = new QName("http://www.example.com/vouchers", "voucher");
    private final static QName _Excursion_QNAME = new QName("http://www.example.com/vouchers", "excursion");
    private final static QName _Travel_QNAME = new QName("http://www.example.com/vouchers", "travel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.vouchers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TouristVouchers }
     * 
     */
    public TouristVouchers createTouristVouchers() {
        return new TouristVouchers();
    }

    /**
     * Create an instance of {@link Voucher }
     * 
     */
    public Voucher createVoucher() {
        return new Voucher();
    }

    /**
     * Create an instance of {@link Excursion }
     * 
     */
    public Excursion createExcursion() {
        return new Excursion();
    }

    /**
     * Create an instance of {@link Travel }
     * 
     */
    public Travel createTravel() {
        return new Travel();
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Voucher }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/vouchers", name = "voucher")
    public JAXBElement<Voucher> createVoucher(Voucher value) {
        return new JAXBElement<Voucher>(_Voucher_QNAME, Voucher.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Excursion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/vouchers", name = "excursion", substitutionHeadNamespace = "http://www.example.com/vouchers", substitutionHeadName = "voucher")
    public JAXBElement<Excursion> createExcursion(Excursion value) {
        return new JAXBElement<Excursion>(_Excursion_QNAME, Excursion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Travel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/vouchers", name = "travel", substitutionHeadNamespace = "http://www.example.com/vouchers", substitutionHeadName = "voucher")
    public JAXBElement<Travel> createTravel(Travel value) {
        return new JAXBElement<Travel>(_Travel_QNAME, Travel.class, null, value);
    }

}
