//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 02:29:46 PM MSK 
//


package com.shchuryk.xml.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Transport-Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Transport-Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="air"/>
 *     &lt;enumeration value="train"/>
 *     &lt;enumeration value="ship"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Transport-Type")
@XmlEnum
public enum TransportType {

    @XmlEnumValue("air")
    AIR("air"),
    @XmlEnumValue("train")
    TRAIN("train"),
    @XmlEnumValue("ship")
    SHIP("ship");
    private final String value;

    TransportType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransportType fromValue(String v) {
        for (TransportType c: TransportType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    @Override
    public String toString() {
        return "TransportType{" +
                "value='" + value + '\'' +
                '}';
    }
}
