
package soapservice.daoTour;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DaoTourBeanService", targetNamespace = "http://daoTour/", wsdlLocation = "http://localhost:8080/DaoTourBeanService/DaoTourBean?wsdl")
public class DaoTourBeanService
    extends Service
{

    private final static URL DAOTOURBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAOTOURBEANSERVICE_EXCEPTION;
    private final static QName DAOTOURBEANSERVICE_QNAME = new QName("http://daoTour/", "DaoTourBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DaoTourBeanService/DaoTourBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAOTOURBEANSERVICE_WSDL_LOCATION = url;
        DAOTOURBEANSERVICE_EXCEPTION = e;
    }

    public DaoTourBeanService() {
        super(__getWsdlLocation(), DAOTOURBEANSERVICE_QNAME);
    }

    public DaoTourBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAOTOURBEANSERVICE_QNAME, features);
    }

    public DaoTourBeanService(URL wsdlLocation) {
        super(wsdlLocation, DAOTOURBEANSERVICE_QNAME);
    }

    public DaoTourBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAOTOURBEANSERVICE_QNAME, features);
    }

    public DaoTourBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaoTourBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DaoTourBean
     */
    @WebEndpoint(name = "DaoTourBeanPort")
    public DaoTourBean getDaoTourBeanPort() {
        return super.getPort(new QName("http://daoTour/", "DaoTourBeanPort"), DaoTourBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DaoTourBean
     */
    @WebEndpoint(name = "DaoTourBeanPort")
    public DaoTourBean getDaoTourBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://daoTour/", "DaoTourBeanPort"), DaoTourBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAOTOURBEANSERVICE_EXCEPTION!= null) {
            throw DAOTOURBEANSERVICE_EXCEPTION;
        }
        return DAOTOURBEANSERVICE_WSDL_LOCATION;
    }

}
