
package soapservice.daoTour;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DaoTourBean", targetNamespace = "http://daoTour/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DaoTourBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns daoTour.ClientEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://daoTour/", className = "daoTour.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://daoTour/", className = "daoTour.UpdateResponse")
    @Action(input = "http://daoTour/DaoTourBean/updateRequest", output = "http://daoTour/DaoTourBean/updateResponse")
    public ClientEntity update(
            @WebParam(name = "arg0", targetNamespace = "")
                    ClientEntity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://daoTour/", className = "daoTour.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://daoTour/", className = "daoTour.DeleteResponse")
    @Action(input = "http://daoTour/DaoTourBean/deleteRequest", output = "http://daoTour/DaoTourBean/deleteResponse")
    public boolean delete(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns daoTour.ClientEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://daoTour/", className = "daoTour.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://daoTour/", className = "daoTour.ReadResponse")
    @Action(input = "http://daoTour/DaoTourBean/readRequest", output = "http://daoTour/DaoTourBean/readResponse")
    public ClientEntity read(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns daoTour.ClientEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://daoTour/", className = "daoTour.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://daoTour/", className = "daoTour.CreateResponse")
    @Action(input = "http://daoTour/DaoTourBean/createRequest", output = "http://daoTour/DaoTourBean/createResponse")
    public ClientEntity create(
            @WebParam(name = "arg0", targetNamespace = "")
                    ClientEntity arg0);

    /**
     * 
     * @return
     *     returns java.util.List<daoTour.TourEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllBurningTours", targetNamespace = "http://daoTour/", className = "daoTour.FindAllBurningTours")
    @ResponseWrapper(localName = "findAllBurningToursResponse", targetNamespace = "http://daoTour/", className = "daoTour.FindAllBurningToursResponse")
    @Action(input = "http://daoTour/DaoTourBean/findAllBurningToursRequest", output = "http://daoTour/DaoTourBean/findAllBurningToursResponse")
    public List<TourEntity> findAllBurningTours();

    /**
     * 
     * @return
     *     returns java.util.List<daoTour.TourEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllTours", targetNamespace = "http://daoTour/", className = "daoTour.FindAllTours")
    @ResponseWrapper(localName = "findAllToursResponse", targetNamespace = "http://daoTour/", className = "daoTour.FindAllToursResponse")
    @Action(input = "http://daoTour/DaoTourBean/findAllToursRequest", output = "http://daoTour/DaoTourBean/findAllToursResponse")
    public List<TourEntity> findAllTours();

}
