package com.shchuryk.util;

public enum AttributeParameterEnum {
    RESULT,
    PAGE_NAME,
    ORDERS,
    COMMAND,
    RACE_NAME_INPUT,
    RACE_DATE_INPUT,
    RACE_NAME_INPUT_FOR_BETS,
    RACE_NAME_INPUT_FOR_REGISTER,
    HORSE_NAME_INPUT_FOR_REGISTER,
    RACE_NAME_INPUT_FOR_RESULT,
    HORSE_NAME_INPUT_FOR_RESULT,
    PLACE_INPUT_FOR_RESULT,
    USERNAME_INPUT_FOR_REGISTER,
    CLIENT_NAME_INPUT_FOR_REGISTER,
    PASSWORD_INPUT_FOR_REGISTER,
    MAIL_INPUT_FOR_REGISTER,
    CONFIRM_PASSWORD_INPUT_FOR_REGISTER,
    USERNAME_INPUT_FOR_LOGIN,
    PASSWORD_INPUT_FOR_LOGIN,
    LAST_SESSION_DATE,
    VISIT_COUNT,
    USER,
    ERR
}
