
package soapservice.daoClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DaoClientBean", targetNamespace = "http://dao/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DaoClientBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns dao.ClientEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://dao/", className = "dao.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://dao/", className = "dao.UpdateResponse")
    @Action(input = "http://dao/DaoClientBean/updateRequest", output = "http://dao/DaoClientBean/updateResponse")
    public ClientEntity update(
            @WebParam(name = "arg0", targetNamespace = "")
                    ClientEntity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://dao/", className = "dao.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://dao/", className = "dao.DeleteResponse")
    @Action(input = "http://dao/DaoClientBean/deleteRequest", output = "http://dao/DaoClientBean/deleteResponse")
    public boolean delete(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns dao.ClientEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://dao/", className = "dao.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://dao/", className = "dao.ReadResponse")
    @Action(input = "http://dao/DaoClientBean/readRequest", output = "http://dao/DaoClientBean/readResponse")
    public ClientEntity read(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns dao.ClientEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://dao/", className = "dao.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://dao/", className = "dao.CreateResponse")
    @Action(input = "http://dao/DaoClientBean/createRequest", output = "http://dao/DaoClientBean/createResponse")
    public ClientEntity create(
            @WebParam(name = "arg0", targetNamespace = "")
                    ClientEntity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<dao.TourEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findClientOrders", targetNamespace = "http://dao/", className = "dao.FindClientOrders")
    @ResponseWrapper(localName = "findClientOrdersResponse", targetNamespace = "http://dao/", className = "dao.FindClientOrdersResponse")
    @Action(input = "http://dao/DaoClientBean/findClientOrdersRequest", output = "http://dao/DaoClientBean/findClientOrdersResponse")
    public List<TourEntity> findClientOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
