
package soapservice.daoClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DaoClientBeanService", targetNamespace = "http://dao/", wsdlLocation = "http://localhost:8080/DaoClientBeanService/DaoClientBean?wsdl")
public class DaoClientBeanService
    extends Service
{

    private final static URL DAOCLIENTBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAOCLIENTBEANSERVICE_EXCEPTION;
    private final static QName DAOCLIENTBEANSERVICE_QNAME = new QName("http://dao/", "DaoClientBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DaoClientBeanService/DaoClientBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAOCLIENTBEANSERVICE_WSDL_LOCATION = url;
        DAOCLIENTBEANSERVICE_EXCEPTION = e;
    }

    public DaoClientBeanService() {
        super(__getWsdlLocation(), DAOCLIENTBEANSERVICE_QNAME);
    }

    public DaoClientBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAOCLIENTBEANSERVICE_QNAME, features);
    }

    public DaoClientBeanService(URL wsdlLocation) {
        super(wsdlLocation, DAOCLIENTBEANSERVICE_QNAME);
    }

    public DaoClientBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAOCLIENTBEANSERVICE_QNAME, features);
    }

    public DaoClientBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaoClientBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DaoClientBean
     */
    @WebEndpoint(name = "DaoClientBeanPort")
    public DaoClientBean getDaoClientBeanPort() {
        return super.getPort(new QName("http://dao/", "DaoClientBeanPort"), DaoClientBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DaoClientBean
     */
    @WebEndpoint(name = "DaoClientBeanPort")
    public DaoClientBean getDaoClientBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao/", "DaoClientBeanPort"), DaoClientBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAOCLIENTBEANSERVICE_EXCEPTION!= null) {
            throw DAOCLIENTBEANSERVICE_EXCEPTION;
        }
        return DAOCLIENTBEANSERVICE_WSDL_LOCATION;
    }

}
